# SwiftLint configuration for EmbedKit

# Paths to include
included:
  - Sources
  - Tests

# Paths to exclude
excluded:
  - .build
  - DerivedData
  - Package.swift
  - Tests/LinuxMain.swift
  - "**/*.generated.swift"

# Rules configuration
disabled_rules:
  - todo # We use TODOs for tracking
  - line_length # Long lines are sometimes necessary
  - type_body_length # Some types are necessarily long
  - file_length # Some files are necessarily long
  - function_body_length # Some functions are complex

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Rule configuration
cyclomatic_complexity:
  warning: 15
  error: 20
  ignores_case_statements: true

force_cast: warning
force_try: warning
force_unwrapping: warning

function_parameter_count:
  warning: 6
  error: 8

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - z

large_tuple:
  warning: 3
  error: 4

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 4

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

unused_import:
  severity: error

vertical_whitespace:
  max_empty_lines: 2

# File header configuration
file_header:
  required_pattern: |
    \/\/
    \/\/  .*\.swift
    \/\/  EmbedKit
    \/\/
    \/\/  Created by .* on .*\.
    \/\/

# Custom rules
custom_rules:
  no_print_statements:
    name: "Print Statements"
    regex: '\bprint\('
    message: "Use proper logging instead of print statements"
    severity: warning
    excluded:
      - "Tests/*"
      - "Sources/EmbedKit/Examples/*"
  
  force_https:
    name: "Force HTTPS"
    regex: '(http(?!s):\/\/(?!localhost))'
    message: "Use HTTPS instead of HTTP"
    severity: error
  
  no_hardcoded_strings:
    name: "No Hardcoded Strings"
    regex: '(NSLocalizedString|LocalizedStringKey)\(@?"[^",]+"'
    message: "Use localized string keys"
    severity: warning
    excluded:
      - "Tests/*"

# Reporter type
reporter: "xcode"