#!/usr/bin/env python3
"""
Generate BPE parity test fixtures for EmbedKit.

Tokenizes a set of edge-case strings using HuggingFace transformers
and outputs a JSON fixture file for Swift parity tests.

Usage:
    pip install transformers
    python Scripts/generate_bpe_fixtures.py

Output:
    Tests/EmbedKitTests/Resources/bpe_parity_fixtures.json
"""

import json
import os
from transformers import AutoTokenizer

# Models to test against
MODELS = {
    "nomic": "nomic-ai/nomic-embed-text-v1.5",
    "bge_m3": "BAAI/bge-m3",
    "llama3": "meta-llama/Meta-Llama-3-8B",
    "mistral": "mistralai/Mistral-7B-v0.1",
}

# Edge-case test strings
TEST_STRINGS = [
    # Basic
    "Hello world",
    "hello world",
    "HELLO WORLD",
    "",
    " ",
    "  ",
    "\n",
    "\t",
    "\r\n",

    # Single characters
    "a",
    "Z",
    "0",
    "!",

    # Contractions (GPT-2 regex edge case)
    "I'm happy",
    "don't stop",
    "she'll be fine",
    "they've gone",
    "we're here",
    "it's a test",
    "I'd rather not",

    # Numbers
    "123",
    "1234",
    "12345",
    "3.14159",
    "1,000,000",
    "$99.99",
    "2024-01-15",

    # Punctuation
    "hello, world!",
    "test...done",
    "a--b",
    "(parentheses)",
    "[brackets]",
    "{braces}",
    "\"quotes\"",
    "it's",
    "rock'n'roll",

    # Unicode / Multilingual
    "cafe\u0301",  # e + combining acute
    "\u00e9",      # precomposed e-acute
    "\u4f60\u597d\u4e16\u754c",  # Chinese: 你好世界
    "\u3053\u3093\u306b\u3061\u306f",  # Japanese: こんにちは
    "\ud55c\uad6d\uc5b4",  # Korean: 한국어
    "\u0410\u043b\u0433\u043e\u0440\u0438\u0442\u043c",  # Russian: Алгоритм
    "\u0645\u0631\u062d\u0628\u0627",  # Arabic: مرحبا

    # Emoji
    "\ud83d\ude00",  # 😀
    "\ud83d\udc4d\ud83c\udffb",  # 👍🏻
    "\ud83d\ude80\ud83c\udf1f\u2728",  # 🚀🌟✨
    "Hello \ud83d\udc4b world \ud83c\udf0d",

    # Code
    "def foo(x: int) -> str:",
    "fn main() { println!(\"Hello\"); }",
    "SELECT * FROM users WHERE id = 1;",
    "https://example.com/path?q=hello&lang=en",
    "user@example.com",
    "<html><body>Hello</body></html>",
    "let x = 42; // comment",

    # Whitespace patterns
    "word   word",
    "  leading",
    "trailing  ",
    "tab\there",
    "line1\nline2",
    "line1\r\nline2",
    "  multiple\n\n  paragraphs  ",

    # Mixed scripts
    "Hello \u4e16\u754c World",
    "price: \u00a5100",
    "caf\u00e9 na\u00efve r\u00e9sum\u00e9",
    "The \u00fc in \u00fcber",

    # Long text
    "The quick brown fox jumps over the lazy dog. " * 5,

    # Repeated characters
    "aaaaaaa",
    "aababab",
    "!!!!!",

    # Edge: bytes that exercise the full byte-to-unicode mapping
    "\x00",  # null byte
    "\x01\x02\x03",  # control characters
    "\x7f",  # DEL
    "\xff",  # Not valid UTF-8 standalone, skip if needed

    # Special token lookalikes
    "[CLS]",
    "<s>",
    "</s>",
    "[UNK]",

    # Sentence pairs (common in embedding models)
    "query: What is machine learning?",
    "search_document: Machine learning is a subset of AI.",
    "clustering: Neural networks are computational models.",
]


def generate_fixtures():
    output = {
        "description": "BPE parity test fixtures generated by HuggingFace transformers",
        "models": {},
    }

    for model_key, model_name in MODELS.items():
        print(f"Loading tokenizer: {model_name}")
        try:
            tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
        except Exception as e:
            print(f"  WARNING: Could not load {model_name}: {e}")
            print(f"  Skipping {model_key}")
            continue

        model_fixtures = {
            "model_name": model_name,
            "vocab_size": tokenizer.vocab_size,
            "test_cases": [],
        }

        for text in TEST_STRINGS:
            try:
                # Encode without special tokens first
                encoded_no_special = tokenizer.encode(text, add_special_tokens=False)
                # Encode with special tokens
                encoded_with_special = tokenizer.encode(text, add_special_tokens=True)
                # Decode back
                decoded = tokenizer.decode(encoded_no_special, skip_special_tokens=True)

                model_fixtures["test_cases"].append({
                    "input": text,
                    "token_ids_no_special": encoded_no_special,
                    "token_ids_with_special": encoded_with_special,
                    "decoded": decoded,
                    "num_tokens": len(encoded_no_special),
                })
            except Exception as e:
                model_fixtures["test_cases"].append({
                    "input": text,
                    "error": str(e),
                })

        output["models"][model_key] = model_fixtures
        print(f"  Generated {len(model_fixtures['test_cases'])} test cases")

    # Write output
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)
    output_dir = os.path.join(project_dir, "Tests", "EmbedKitTests", "Resources")
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, "bpe_parity_fixtures.json")

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    print(f"\nFixtures written to: {output_path}")
    print(f"Total models: {len(output['models'])}")


if __name__ == "__main__":
    generate_fixtures()
